-- Your SQL goes here

CREATE TABLE "email" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "user" INTEGER NOT NULL UNIQUE, 
    "email_record" VARCHAR(255) NOT NULL,
	PRIMARY KEY("id"),
	CONSTRAINT "fk_user_email"
        FOREIGN KEY ("user") REFERENCES "users" ("id")
        ON DELETE CASCADE
);
